### ISSUE TITLE
Document how to only run pre-push with the pre-commit integration

### ISSUE THREAD

**Issue by davetapley** [pylint-dev/pylint#9924]
### Question

The [pre-commit integration docs](https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html#pre-commit-integration) helpfully say:

> [..] pylint -- due to its speed -- is more suited to a [..] git pre-push hook

And then gives an example `.pre-commit-config.yaml` which _doesn't_ specify `stages: [push]`.

As someone who isn't familiar with `.pre-commit-config.yaml` it took some digging to find the [relevant documentation for pre-commit](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages).

Would a PR be welcome to make include here?

### Documentation for future user

Link to the [relevant documentation for pre-commit](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages).

A  `.pre-commit-config.yaml` which includes `stages`:
```yml
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      stages: [push]
      require_serial: true
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
```
